// Code generated by sqlc. DO NOT EDIT.
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPlatformAnalytics = `-- name: GetPlatformAnalytics :one
SELECT 
    (SELECT COUNT(*) FROM orders) as total_orders,
    (SELECT COUNT(*) FROM vendors) as total_vendors,
    (SELECT COALESCE(SUM(total_amount), 0) FROM orders WHERE status = 'delivered') as total_revenue
`

type GetPlatformAnalyticsRow struct {
	TotalOrders  int64          `json:"total_orders"`
	TotalVendors int64          `json:"total_vendors"`
	TotalRevenue pgtype.Numeric `json:"total_revenue"`
}

func (q *Queries) GetPlatformAnalytics(ctx context.Context) (GetPlatformAnalyticsRow, error) {
	row := q.db.QueryRow(ctx, getPlatformAnalytics)
	var i GetPlatformAnalyticsRow
	err := row.Scan(&i.TotalOrders, &i.TotalVendors, &i.TotalRevenue)
	return i, err
}
