// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: menu_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMenuItem = `-- name: CreateMenuItem :one
INSERT INTO menu_items (vendor_id, name, price, stock_qty, is_available)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, vendor_id, name, price, stock_qty, is_available
`

type CreateMenuItemParams struct {
	VendorID    pgtype.UUID    `json:"vendor_id"`
	Name        string         `json:"name"`
	Price       pgtype.Numeric `json:"price"`
	StockQty    int32          `json:"stock_qty"`
	IsAvailable bool           `json:"is_available"`
}

func (q *Queries) CreateMenuItem(ctx context.Context, arg CreateMenuItemParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, createMenuItem,
		arg.VendorID,
		arg.Name,
		arg.Price,
		arg.StockQty,
		arg.IsAvailable,
	)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Price,
		&i.StockQty,
		&i.IsAvailable,
	)
	return i, err
}

const getMenuItemByID = `-- name: GetMenuItemByID :one
SELECT id, vendor_id, name, price, stock_qty, is_available FROM menu_items
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetMenuItemByID(ctx context.Context, id pgtype.UUID) (MenuItem, error) {
	row := q.db.QueryRow(ctx, getMenuItemByID, id)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Price,
		&i.StockQty,
		&i.IsAvailable,
	)
	return i, err
}

const listMenuItemsByVendor = `-- name: ListMenuItemsByVendor :many
SELECT id, vendor_id, name, price, stock_qty, is_available FROM menu_items
WHERE vendor_id = $1
ORDER BY name ASC
LIMIT $2 OFFSET $3
`

type ListMenuItemsByVendorParams struct {
	VendorID pgtype.UUID `json:"vendor_id"`
	Limit    int32       `json:"limit"`
	Offset   int32       `json:"offset"`
}

func (q *Queries) ListMenuItemsByVendor(ctx context.Context, arg ListMenuItemsByVendorParams) ([]MenuItem, error) {
	rows, err := q.db.Query(ctx, listMenuItemsByVendor, arg.VendorID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []MenuItem
	for rows.Next() {
		var i MenuItem
		if err := rows.Scan(
			&i.ID,
			&i.VendorID,
			&i.Name,
			&i.Price,
			&i.StockQty,
			&i.IsAvailable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMenuItemPrice = `-- name: UpdateMenuItemPrice :one
UPDATE menu_items
SET price = $2
WHERE id = $1
RETURNING id, vendor_id, name, price, stock_qty, is_available
`

type UpdateMenuItemPriceParams struct {
	ID    pgtype.UUID    `json:"id"`
	Price pgtype.Numeric `json:"price"`
}

func (q *Queries) UpdateMenuItemPrice(ctx context.Context, arg UpdateMenuItemPriceParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItemPrice, arg.ID, arg.Price)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Price,
		&i.StockQty,
		&i.IsAvailable,
	)
	return i, err
}

const updateMenuItemStock = `-- name: UpdateMenuItemStock :one
UPDATE menu_items
SET stock_qty = $2
WHERE id = $1
RETURNING id, vendor_id, name, price, stock_qty, is_available
`

type UpdateMenuItemStockParams struct {
	ID       pgtype.UUID `json:"id"`
	StockQty int32       `json:"stock_qty"`
}

func (q *Queries) UpdateMenuItemStock(ctx context.Context, arg UpdateMenuItemStockParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, updateMenuItemStock, arg.ID, arg.StockQty)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Price,
		&i.StockQty,
		&i.IsAvailable,
	)
	return i, err
}

const decrementMenuItemStock = `-- name: DecrementMenuItemStock :one
UPDATE menu_items
SET stock_qty = stock_qty - $2
WHERE id = $1 AND stock_qty >= $2
RETURNING id, vendor_id, name, price, stock_qty, is_available
`

type DecrementMenuItemStockParams struct {
	ID       pgtype.UUID `json:"id"`
	StockQty int32       `json:"stock_qty"`
}

func (q *Queries) DecrementMenuItemStock(ctx context.Context, arg DecrementMenuItemStockParams) (MenuItem, error) {
	row := q.db.QueryRow(ctx, decrementMenuItemStock, arg.ID, arg.StockQty)
	var i MenuItem
	err := row.Scan(
		&i.ID,
		&i.VendorID,
		&i.Name,
		&i.Price,
		&i.StockQty,
		&i.IsAvailable,
	)
	return i, err
}
