// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id, vendor_id, status, total_amount, idempotency_key)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, customer_id, vendor_id, status, total_amount, idempotency_key, created_at, updated_at
`

type CreateOrderParams struct {
	CustomerID     pgtype.UUID    `json:"customer_id"`
	VendorID       pgtype.UUID    `json:"vendor_id"`
	Status         string         `json:"status"`
	TotalAmount    pgtype.Numeric `json:"total_amount"`
	IdempotencyKey string         `json:"idempotency_key"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.CustomerID,
		arg.VendorID,
		arg.Status,
		arg.TotalAmount,
		arg.IdempotencyKey,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VendorID,
		&i.Status,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT id, customer_id, vendor_id, status, total_amount, idempotency_key, created_at, updated_at FROM orders
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOrderByID(ctx context.Context, id pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VendorID,
		&i.Status,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByIdempotencyKey = `-- name: GetOrderByIdempotencyKey :one
SELECT id, customer_id, vendor_id, status, total_amount, idempotency_key, created_at, updated_at FROM orders
WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetOrderByIdempotencyKey(ctx context.Context, idempotencyKey string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByIdempotencyKey, idempotencyKey)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VendorID,
		&i.Status,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listOrdersByCustomer = `-- name: ListOrdersByCustomer :many
SELECT id, customer_id, vendor_id, status, total_amount, idempotency_key, created_at, updated_at FROM orders
WHERE customer_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByCustomer(ctx context.Context, customerID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByCustomer, customerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VendorID,
			&i.Status,
			&i.TotalAmount,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrdersByVendor = `-- name: ListOrdersByVendor :many
SELECT id, customer_id, vendor_id, status, total_amount, idempotency_key, created_at, updated_at FROM orders
WHERE vendor_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListOrdersByVendor(ctx context.Context, vendorID pgtype.UUID) ([]Order, error) {
	rows, err := q.db.Query(ctx, listOrdersByVendor, vendorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.VendorID,
			&i.Status,
			&i.TotalAmount,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOrderStatus = `-- name: UpdateOrderStatus :one
UPDATE orders
SET status = $2, updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, customer_id, vendor_id, status, total_amount, idempotency_key, created_at, updated_at
`

type UpdateOrderStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateOrderStatus(ctx context.Context, arg UpdateOrderStatusParams) (Order, error) {
	row := q.db.QueryRow(ctx, updateOrderStatus, arg.ID, arg.Status)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.VendorID,
		&i.Status,
		&i.TotalAmount,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
