// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: order_items.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, menu_item_id, qty, price_at_order_time)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, menu_item_id, qty, price_at_order_time
`

type CreateOrderItemParams struct {
	OrderID          pgtype.UUID    `json:"order_id"`
	MenuItemID       pgtype.UUID    `json:"menu_item_id"`
	Qty              int32          `json:"qty"`
	PriceAtOrderTime pgtype.Numeric `json:"price_at_order_time"`
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.MenuItemID,
		arg.Qty,
		arg.PriceAtOrderTime,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.MenuItemID,
		&i.Qty,
		&i.PriceAtOrderTime,
	)
	return i, err
}

const listOrderItemsByOrder = `-- name: ListOrderItemsByOrder :many
SELECT id, order_id, menu_item_id, qty, price_at_order_time FROM order_items
WHERE order_id = $1
`

func (q *Queries) ListOrderItemsByOrder(ctx context.Context, orderID pgtype.UUID) ([]OrderItem, error) {
	rows, err := q.db.Query(ctx, listOrderItemsByOrder, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OrderItem
	for rows.Next() {
		var i OrderItem
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.MenuItemID,
			&i.Qty,
			&i.PriceAtOrderTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
