// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: vendors.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVendor = `-- name: CreateVendor :one
INSERT INTO vendors (user_id, name, address, is_open)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, address, is_open, created_at
`

type CreateVendorParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Name    string      `json:"name"`
	Address string      `json:"address"`
	IsOpen  bool        `json:"is_open"`
}

func (q *Queries) CreateVendor(ctx context.Context, arg CreateVendorParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, createVendor,
		arg.UserID,
		arg.Name,
		arg.Address,
		arg.IsOpen,
	)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Address,
		&i.IsOpen,
		&i.CreatedAt,
	)
	return i, err
}

const getVendorByID = `-- name: GetVendorByID :one
SELECT id, user_id, name, address, is_open, created_at FROM vendors
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetVendorByID(ctx context.Context, id pgtype.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByID, id)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Address,
		&i.IsOpen,
		&i.CreatedAt,
	)
	return i, err
}

const getVendorByUserID = `-- name: GetVendorByUserID :one
SELECT id, user_id, name, address, is_open, created_at FROM vendors
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetVendorByUserID(ctx context.Context, userID pgtype.UUID) (Vendor, error) {
	row := q.db.QueryRow(ctx, getVendorByUserID, userID)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Address,
		&i.IsOpen,
		&i.CreatedAt,
	)
	return i, err
}

const listVendors = `-- name: ListVendors :many
SELECT id, user_id, name, address, is_open, created_at FROM vendors
ORDER BY created_at DESC
`

func (q *Queries) ListVendors(ctx context.Context) ([]Vendor, error) {
	rows, err := q.db.Query(ctx, listVendors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vendor
	for rows.Next() {
		var i Vendor
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Address,
			&i.IsOpen,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateVendorStatus = `-- name: UpdateVendorStatus :one
UPDATE vendors
SET is_open = $2
WHERE id = $1
RETURNING id, user_id, name, address, is_open, created_at
`

type UpdateVendorStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	IsOpen bool        `json:"is_open"`
}

func (q *Queries) UpdateVendorStatus(ctx context.Context, arg UpdateVendorStatusParams) (Vendor, error) {
	row := q.db.QueryRow(ctx, updateVendorStatus, arg.ID, arg.IsOpen)
	var i Vendor
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Address,
		&i.IsOpen,
		&i.CreatedAt,
	)
	return i, err
}
